export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS'
export const GET_MOVIES_ERROR = 'GET_MOVIES_ERROR'
export const GET_MOVIES_LOADING = 'GET_MOVIES_LOADING'

export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS'
export const GET_MOVIE_ERROR = 'GET_MOVIE_ERROR'
export const GET_MOVIE_LOADING = 'GET_MOVIE_LOADING'